build:
	mkdir -p bin && gcc -Wall -o bin/p p.c

ch5:
	mkdir -p bin && gcc -Wall -g -o bin/ch5 ch5.c

beej:
	mkdir -p bin && gcc -Wall -Wextra -std=c2x -pedantic -g -o bin/beej beej.c 

pp:
	mkdir -p bin && gcc -Wall -Wextra -std=c2x -pedantic -g -o bin/pp pp.c 
